server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${URL}
          default-label: ${LABEL}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true